#!/bin/sh
# This script is executed once after the module is installed by JeVois if it was added to the jevois/packages/ directory
# of the microSD card as a .jvpkg file. The script is deleted from the microSD card after execution.
#
# The caller script will set the current directory to the location of this script before launching the script.

# Add our video mappings to the main mappings file:
jevois-add-videomapping YUYV 640 290 30.0 YUYV 320 240 30.0 SamuelCarbone FirstVision_Simplified

# Example of a simple message:
echo "FirstVision_Simplified is now installed"
